"""Restituye las tildes que el SAES omite en los nombres de las materias ("TEORIA DE LOS CIRCUITOS").

Solo reemplaza palabras completas en MAYÚSCULAS que aparecen en el diccionario, así que no afecta
claves (B207), grupos (2BV2), llaves JSON ni nombres de profesores. Las comparaciones en la página usan
norm() (sin acentos), por lo que el emparejamiento con los datos del SAES no cambia.
"""
import re

PALABRAS = """
ADMINISTRACION:ADMINISTRACIÓN AERODINAMICA:AERODINÁMICA ALGEBRA:ÁLGEBRA ANALISIS:ANÁLISIS ANALOGICA:ANALÓGICA
ANATOMIA:ANATOMÍA AUTOMATAS:AUTÓMATAS AUTOMATIZACION:AUTOMATIZACIÓN AUTOMOVIL:AUTOMÓVIL AUTOMOVILES:AUTOMÓVILES
AUTONOMA:AUTÓNOMA BASICO:BÁSICO BASICA:BÁSICA BIODINAMICA:BIODINÁMICA BIOELECTRONICA:BIOELECTRÓNICA
BIOESTADISTICA:BIOESTADÍSTICA BIOETICA:BIOÉTICA BIOFISICA:BIOFÍSICA BIOINSTRUMENTACION:BIOINSTRUMENTACIÓN
BIOLOGIA:BIOLOGÍA BIOLOGICAS:BIOLÓGICAS BIOLOGICOS:BIOLÓGICOS BIOMECANICA:BIOMECÁNICA BIOMECANICOS:BIOMECÁNICOS
BIOMEDICA:BIOMÉDICA BIOMIMETICAS:BIOMIMÉTICAS BIOMIMETICOS:BIOMIMÉTICOS BIONICA:BIÓNICA BIONICOS:BIÓNICOS
BIOQUIMICA:BIOQUÍMICA BIOROBOTICA:BIOROBÓTICA BIOTECNOLOGICA:BIOTECNOLÓGICA CALCULO:CÁLCULO
CARACTERIZACION:CARACTERIZACIÓN CLASICO:CLÁSICO CLASICA:CLÁSICA CLINICA:CLÍNICA COMUNICACION:COMUNICACIÓN
CRIPTOGRAFIA:CRIPTOGRAFÍA DINAMICA:DINÁMICA ECONOMIA:ECONOMÍA ECONOMICA:ECONÓMICA ELECTRICA:ELÉCTRICA
ELECTRICAS:ELÉCTRICAS ELECTRICOS:ELÉCTRICOS ELECTROMAGNETICA:ELECTROMAGNÉTICA ELECTROMAGNETICAS:ELECTROMAGNÉTICAS
ELECTRONICA:ELECTRÓNICA ELECTRONICOS:ELECTRÓNICOS ENERGIA:ENERGÍA ENERGETICA:ENERGÉTICA ENERGETICOS:ENERGÉTICOS
ERGONOMIA:ERGONOMÍA ERGONOMICO:ERGONÓMICO ESTADISTICA:ESTADÍSTICA ESTATICA:ESTÁTICA ETICA:ÉTICA
EVALUACION:EVALUACIÓN FABRICACION:FABRICACIÓN FISICA:FÍSICA FISICOQUIMICA:FISICOQUÍMICA FISIOANATOMIA:FISIOANATOMÍA
FISIOLOGIA:FISIOLOGÍA GENERACION:GENERACIÓN GEOGRAFICA:GEOGRÁFICA GESTION:GESTIÓN GLOBALIZACION:GLOBALIZACIÓN
GRAFICACION:GRAFICACIÓN HIDRAULICA:HIDRÁULICA IMAGENES:IMÁGENES IMAGENOLOGIA:IMAGENOLOGÍA
IMPLEMENTACION:IMPLEMENTACIÓN INALAMBRICAS:INALÁMBRICAS INFORMACION:INFORMACIÓN INFORMATICA:INFORMÁTICA
INGENIERIA:INGENIERÍA INGLES:INGLÉS INSTRUMENTACION:INSTRUMENTACIÓN INTEGRACION:INTEGRACIÓN
INTRODUCCION:INTRODUCCIÓN INVERSION:INVERSIÓN INVESTIGACION:INVESTIGACIÓN LINEA:LÍNEA LINEAS:LÍNEAS
LOGICA:LÓGICA LOGICOS:LÓGICOS LOGISTICA:LOGÍSTICA MAQUINAS:MÁQUINAS MATEMATICAS:MATEMÁTICAS
MATEMATICOS:MATEMÁTICOS MECANICA:MECÁNICA MECANICOS:MECÁNICOS MECATRONICA:MECATRÓNICA MECATRONICOS:MECATRÓNICOS
MEDICA:MÉDICA METODOLOGIA:METODOLOGÍA METODOS:MÉTODOS METROLOGIA:METROLOGÍA MEXICO:MÉXICO MOVILES:MÓVILES
NEUMATICA:NEUMÁTICA NEUROROBOTICA:NEUROROBÓTICA NUMERICO:NUMÉRICO NUMERICOS:NUMÉRICOS NUMEROS:NÚMEROS
OLEONEUMATICA:OLEONEUMÁTICA OPTICA:ÓPTICA OPTIMATIZACION:OPTIMATIZACIÓN OPTIMIZACION:OPTIMIZACIÓN
ORGANICA:ORGÁNICA INORGANICA:INORGÁNICA ORGANIZACION:ORGANIZACIÓN PARTICULA:PARTÍCULA PROFESION:PROFESIÓN
PROGRAMACION:PROGRAMACIÓN PROPAGACION:PROPAGACIÓN PRODUCCION:PRODUCCIÓN PROTESIS:PRÓTESIS QUIMICA:QUÍMICA
REINGENIERIA:REINGENIERÍA RIGIDO:RÍGIDO ROBOTICA:ROBÓTICA ROBOTICO:ROBÓTICO ROBOTICOS:ROBÓTICOS
SIMULACION:SIMULACIÓN SINTESIS:SÍNTESIS TECNICAS:TÉCNICAS TECNOLOGIA:TECNOLOGÍA TECNOLOGIAS:TECNOLOGÍAS
TECNOLOGICA:TECNOLÓGICA TELEFONIA:TELEFONÍA TELEMATICA:TELEMÁTICA TELEMATICOS:TELEMÁTICOS TELEMETRIA:TELEMETRÍA
TELEVISION:TELEVISIÓN TEORIA:TEORÍA TERMODINAMICA:TERMODINÁMICA TOPICOS:TÓPICOS TRANSMISION:TRANSMISIÓN
TRIBOLOGIA:TRIBOLOGÍA UNION:UNIÓN VEHICULO:VEHÍCULO VEHICULOS:VEHÍCULOS VISION:VISIÓN
"""
MAPA = dict(par.split(":") for par in PALABRAS.split())
_PAL = re.compile(r"(?<![A-Za-zÁÉÍÓÚÑÜáéíóúñü])[A-ZÁÉÍÓÚÑÜ]{2,}(?![A-Za-zÁÉÍÓÚÑÜáéíóúñü])")


_T = {"A": "Á", "E": "É", "I": "Í", "O": "Ó", "U": "Ú"}
_NO = {"COMUNICA", "ABRICA"}   # abreviaturas del SAES («COMUNICA.», «F-ABRICA»)


def regla(w: str):
    """Tilde por regla ortográfica para palabras que no están en el diccionario: -CIÓN/-SIÓN, -LOGÍA/-GRAFÍA/-METRÍA/
    -NOMÍA/-TOMÍA/-SOFÍA y esdrújulas en -ICO/-ICA (DINÁMICOS, FARMACÉUTICA). Solo para nombres de materias y carreras:
    no se aplica a apellidos de profesores."""
    if w in MAPA or w in _NO or len(w) < 5 or re.search("[ÁÉÍÓÚ]", w):
        return None
    m = re.match(r"^(.*)([CS])ION$", w)
    if m:
        return m.group(1) + m.group(2) + "IÓN"
    m = re.match(r"^(.*(?:LOG|GRAF|METR|NOM|TOM|SOF))IA(S?)$", w)
    if m:
        return m.group(1) + "ÍA" + m.group(2)
    m = re.match(r"^(.*?)([AEIOU])([^AEIOU]+)(IC[OA]S?)$", w)
    if m:
        pre, v, cons, suf = m.groups()
        if v in "IU" and pre and pre[-1] in "AEO":   # diptongo: la tilde va en la vocal fuerte (FARMACÉUTICA)
            return pre[:-1] + _T[pre[-1]] + v + cons + suf
        return pre + _T[v] + cons + suf
    return None


def acentuar_nombre(texto: str) -> str:
    """Diccionario y reglas ortográficas: para nombres de materias, carreras y líneas."""
    return _PAL.sub(lambda m: MAPA.get(m.group(0)) or regla(m.group(0)) or m.group(0), texto)


def acentuar(texto: str) -> str:
    """Pone las tildes a las palabras en mayúsculas del diccionario; lo demás queda igual."""
    return _PAL.sub(lambda m: MAPA.get(m.group(0), m.group(0)), texto)


if __name__ == "__main__":
    for t in ["TEORIA DE LOS CIRCUITOS", "FISICA MODERNA Y OPTICA", "PROCESAMIENTO DE IMAGENES", "INGLES II", "2BV2 B207",
              "SISTEMAS DINAMICOS", "QUIMICA FARMACEUTICA", "MICROBIOLOGIA", "PLANEACION ESTRATEGICA", "COMUNICA. ORAL"]:
        print(t, "->", acentuar_nombre(t))
